version: "3.9"
services:
  db:
    platform: linux/x86_64 # M1チップ向け
    image: mysql:8.0
    volumes:
      - ./tmp/mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/alpha-blog
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development #ローカルならこれは必須
    depends_on:
      - db
    stdin_open: true
    tty: true